model: audits/mechet_reactseq/flower_full/overfit_32/model_step_100.pt
src: datasets/mechet_reactseq_audit/flower_full/overfit_32/test/src.txt
output: audits/mechet_reactseq/flower_full/overfit_32/raw_predictions.txt
gpu: -1
beam_size: 10
n_best: 10
batch_size: 4096
batch_type: tokens
max_length: 160
seed: 0
