#!/usr/bin/env python3
"""Build a pure-Qwen multiple-choice smoke over grounded electron-flow events."""
from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import sys

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from mechet.grounded_event_smoke import grounded_event_task


def read_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--seed", type=int, default=17)
    parser.add_argument("--max-candidates", type=int, default=8)
    parser.add_argument("--minimum-candidates", type=int, default=2)
    parser.add_argument("--limit-events", type=int, default=0)
    args = parser.parse_args()

    rows = read_jsonl(args.data)
    tasks: list[dict] = []
    excluded: Counter[str] = Counter()
    attempted = 0
    for row in rows:
        steps = list(((row.get("metadata") or {}).get("trace_plan") or {}).get("steps") or [])
        for event_index in range(len(steps)):
            if args.limit_events and attempted >= args.limit_events:
                break
            attempted += 1
            try:
                task = grounded_event_task(
                    row,
                    event_index,
                    seed=args.seed,
                    max_candidates=args.max_candidates,
                )
            except Exception as exc:
                excluded[type(exc).__name__ + ":" + str(exc)] += 1
                continue
            if int(task["candidate_count"]) < args.minimum_candidates:
                excluded["INSUFFICIENT_EXECUTABLE_NEGATIVES"] += 1
                continue
            tasks.append(task)
        if args.limit_events and attempted >= args.limit_events:
            break

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "".join(json.dumps(task, ensure_ascii=False) + "\n" for task in tasks),
        encoding="utf-8",
    )
    candidate_counts = Counter(int(task["candidate_count"]) for task in tasks)
    report = {
        "artifact_type": "pure_qwen_grounded_event_smoke_v1",
        "source": str(args.data),
        "seed": args.seed,
        "attempted_events": attempted,
        "eligible_events": len(tasks),
        "excluded_events": attempted - len(tasks),
        "candidate_count_distribution": dict(sorted(candidate_counts.items())),
        "events_with_at_least_4_candidates": sum(
            int(task["candidate_count"]) >= 4 for task in tasks
        ),
        "events_with_8_candidates": sum(
            int(task["candidate_count"]) == 8 for task in tasks
        ),
        "excluded_reasons": dict(excluded.most_common()),
        "claim_boundary": (
            "F-oracle gold-state capability smoke. Hard negatives are generated by "
            "local perturbations of the reference event and filtered only by executor "
            "formal execution; this is not product-only endpoint evaluation."
        ),
    }
    report_path = args.output.with_suffix(".report.json")
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report), flush=True)
    return 0 if tasks else 2


if __name__ == "__main__":
    raise SystemExit(main())
